"use client";
import "./globals.css";
import React from "react";
import MyThemeProvider from "@/components/ThemeProvider";
import SearchAppBar from "@/components/Navbar";
import Container from "@mui/material/Container";
import NavbarCategories from "@/components/Navbar/NavbarCategories";
import Footer from "@/components/Footer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryClientProvider client={queryClient}>
      <MyThemeProvider>
        <html lang="en">
          <body>
            <NavbarCategories />
            <SearchAppBar />
            {children}
            <Footer />
          </body>
        </html>
      </MyThemeProvider>
    </QueryClientProvider>
  );
}
