"use client";
import "./globals.css";
import React from "react";
import MyThemeProvider from "@/components/ThemeProvider";
import SearchAppBar from "@/components/Navbar";
import NavbarCategories from "@/components/Navbar/NavbarCategories";
import Footer from "@/components/Footer";
import { GoogleOAuthProvider } from "@react-oauth/google";
import ProgressProvider from "@/components/ProgressProvider";
import { SessionProvider } from "next-auth/react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import CustomQueryClient from "@/components/QueryClient";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionProvider>
      <CustomQueryClient>
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT as string}
        >
          <MyThemeProvider>
            <html lang="en">
              <body>
                <ProgressProvider>
                  <ToastContainer />
                  {children}
                  {/* <SearchAppBar />
                  <NavbarCategories />
                  <div style={{ minHeight: "100vh" }}>{children}</div>
                  <Footer /> */}
                </ProgressProvider>
              </body>
            </html>
          </MyThemeProvider>
        </GoogleOAuthProvider>
      </CustomQueryClient>
    </SessionProvider>
  );
}
