"use client";
import "./globals.css";
import React from "react";
import MyThemeProvider from "@/components/ThemeProvider";
import SearchAppBar from "@/components/Navbar";
import NavbarCategories from "@/components/Navbar/NavbarCategories";
import Footer from "@/components/Footer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryClientProvider client={queryClient}>
      <GoogleOAuthProvider
        clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT as string}
      >
        <MyThemeProvider>
          <html lang="en">
            <body>
              <SearchAppBar />
              <NavbarCategories />
              <div style={{minHeight:"100vh"}}>
              {children}
              </div>
              <Footer />
            </body>
          </html>
        </MyThemeProvider>
      </GoogleOAuthProvider>
    </QueryClientProvider>
  );
}
